import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireModule } from "@/lib/session";
import { PageHeader } from "@/components/ui/page-header";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export const dynamic = "force-dynamic";
function stringList(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
export default async function ProspectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireModule("PROSPECCAO"); const { id } = await params;
  const prospect = await prisma.prospect.findFirst({ where: { id, tenantId: "default" }, include: { assignedAgent: true, salesOwner: true, contacts: { orderBy: [{ isPrimary: "desc" }, { foundAt: "desc" }] }, sources: { orderBy: { foundAt: "desc" } }, signals: { orderBy: { observedAt: "desc" } }, briefs: { include: { agent: true }, orderBy: { createdAt: "desc" } }, communicationThreads: { include: { messages: { orderBy: { createdAt: "desc" }, take: 20 } }, orderBy: { updatedAt: "desc" } }, outreachEnrollments: { include: { cadence: true } } } });
  if (!prospect) notFound();
  const links = [["Site", prospect.website], ["Instagram", prospect.instagram], ["LinkedIn", prospect.linkedin], ["Facebook", prospect.facebook]].filter((entry): entry is [string, string] => Boolean(entry[1]));
  return <div className="space-y-6"><PageHeader title={prospect.companyName} description={`${prospect.segment || "Segmento não informado"} · ${[prospect.city, prospect.state].filter(Boolean).join("/") || "Local não informado"}`}><Button asChild variant="ghost"><Link href="/dashboard/prospeccao"><ArrowLeft /> Voltar</Link></Button></PageHeader>
    <div className="grid gap-3 md:grid-cols-4"><Card className="p-5"><p className="text-sm text-muted-foreground">Score geral</p><p className="mt-2 text-3xl font-semibold">{prospect.overallScore}</p><Badge className="mt-2">{prospect.qualification}</Badge></Card><Card className="p-5"><p className="text-sm text-muted-foreground">Telun M+</p><p className="mt-2 text-3xl font-semibold">{prospect.marketingFitScore}</p></Card><Card className="p-5"><p className="text-sm text-muted-foreground">Telun Tecnologia</p><p className="mt-2 text-3xl font-semibold">{prospect.technologyFitScore}</p></Card><Card className="p-5"><p className="text-sm text-muted-foreground">Destino / status</p><p className="mt-2 font-semibold">{prospect.businessFit}</p><Badge className="mt-2">{prospect.status}</Badge></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Empresa e canais públicos</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">CNPJ</dt><dd>{prospect.cnpj || "—"}</dd></div><div><dt className="text-muted-foreground">Responsável</dt><dd>{prospect.assignedAgent?.name || prospect.salesOwner?.name || "—"}</dd></div><div><dt className="text-muted-foreground">Telefone</dt><dd>{prospect.commercialPhone || "—"}</dd></div><div><dt className="text-muted-foreground">WhatsApp</dt><dd>{prospect.commercialWhatsApp || "—"}</dd></div><div><dt className="text-muted-foreground">E-mail</dt><dd>{prospect.commercialEmail || "—"}</dd></div><div><dt className="text-muted-foreground">Não contatar</dt><dd>{prospect.doNotContact ? "Sim" : "Não"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{links.map(([label, href]) => <Button key={label} asChild size="sm" variant="outline"><a href={href.startsWith("http") ? href : `https://${href}`} target="_blank" rel="noreferrer">{label} <ExternalLink /></a></Button>)}</div></Card>
    <Card className="p-5"><h2 className="font-semibold">Dores e sinais</h2><div className="mt-4 space-y-4 text-sm"><div><p className="text-muted-foreground">Dores</p><div className="mt-1 flex flex-wrap gap-1">{stringList(prospect.painPoints).map((item) => <Badge key={item} tone="warning">{item}</Badge>)}</div></div><div><p className="text-muted-foreground">Sinais de marketing</p><p>{stringList(prospect.digitalSignals).join(" · ") || "—"}</p></div><div><p className="text-muted-foreground">Sinais de tecnologia</p><p>{stringList(prospect.technologySignals).join(" · ") || "—"}</p></div><p className="text-muted-foreground">{prospect.qualificationReason}</p></div></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Contatos e proveniência</h2><div className="mt-4 space-y-3">{prospect.contacts.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-2"><b>{item.type}: {item.value}</b><Badge>{item.verificationStatus}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.source} · confiança {Math.round(item.confidence * 100)}% · {item.foundAt.toLocaleDateString("pt-BR")}</p></div>)}{prospect.contacts.length === 0 && <p className="text-sm text-muted-foreground">Nenhum contato público registrado.</p>}</div></Card>
    <Card className="p-5"><h2 className="font-semibold">Briefings BDR</h2><div className="mt-4 space-y-3">{prospect.briefs.map((brief) => <div key={brief.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between"><b>{brief.title}</b><span className="text-muted-foreground">{brief.agent.name}</span></div><p className="mt-2">{brief.summary}</p>{brief.draft && <p className="mt-2 whitespace-pre-wrap rounded bg-muted p-3 text-xs">{brief.draft}</p>}</div>)}{prospect.briefs.length === 0 && <p className="text-sm text-muted-foreground">Aguardando handoff ou briefing de Rafael.</p>}</div></Card></div>
    <Card className="p-5"><h2 className="font-semibold">Histórico de comunicação</h2><div className="mt-4 space-y-2">{prospect.communicationThreads.flatMap((thread) => thread.messages).map((message) => <div key={message.id} className="flex gap-3 rounded-lg border p-3 text-sm"><Badge tone={message.direction === "INBOUND" ? "info" : "neutral"}>{message.direction}</Badge><div><p>{message.message}</p><p className="mt-1 text-xs text-muted-foreground">{message.provider} · {message.status} · {message.createdAt.toLocaleString("pt-BR")}</p></div></div>)}{prospect.communicationThreads.length === 0 && <p className="text-sm text-muted-foreground">Nenhuma comunicação registrada.</p>}</div></Card>
  </div>;
}
